
#!/bin/bash
lxc-start -d -n debLXC2101 
lxc-start -d -n debLXC2102 
lxc-start -d -n debLXC2103 
lxc-start -d -n debLXC2104 
lxc-start -d -n debLXC2105 
lxc-start -d -n debLXC2106 
lxc-start -d -n debLXC2107 
lxc-start -d -n debLXC2108 
lxc-start -d -n debLXC2109 
lxc-start -d -n debLXC2110 
lxc-start -d -n debLXC2111 
lxc-start -d -n debLXC2112 
lxc-start -d -n debLXC2113 
lxc-start -d -n debLXC2114 
lxc-start -d -n debLXC2115 
lxc-start -d -n debLXC2116 
lxc-start -d -n debLXC2117 
lxc-start -d -n debLXC2118 
lxc-start -d -n debLXC2119 
lxc-start -d -n debLXC2120 
lxc-start -d -n debLXC2121 
lxc-start -d -n debLXC2122 
lxc-start -d -n debLXC2123 
lxc-start -d -n debLXC2124 
lxc-start -d -n debLXC2125 

lxc-attach -n debLXC2101 -- apt-get -y update && lxc-attach -n debLXC2101 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2101 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2101 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2101 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2102 -- apt-get -y update && lxc-attach -n debLXC2102 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2102 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2102 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2102 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2103 -- apt-get -y update && lxc-attach -n debLXC2103 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2103 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2103 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2103 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ & 
lxc-attach -n debLXC2104 -- apt-get -y update && lxc-attach -n debLXC2104 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2104 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2104 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2104 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2105 -- apt-get -y update && lxc-attach -n debLXC2105 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2105 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2105 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2105 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2106 -- apt-get -y update && lxc-attach -n debLXC2106 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2106 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2106 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2106 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2107 -- apt-get -y update && lxc-attach -n debLXC2107 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2107 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2107 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2107 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2108 -- apt-get -y update && lxc-attach -n debLXC2108 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2108 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2108 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2108 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2109 -- apt-get -y update && lxc-attach -n debLXC2109 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2109 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2109 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2109 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2110 -- apt-get -y update && lxc-attach -n debLXC2110 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2110 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2110 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2110 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2111 -- apt-get -y update && lxc-attach -n debLXC2111 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2111 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2111 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2111 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2112 -- apt-get -y update && lxc-attach -n debLXC2112 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2112 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2112 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2112 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2113 -- apt-get -y update && lxc-attach -n debLXC2113 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2113 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2113 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2113 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2114 -- apt-get -y update && lxc-attach -n debLXC2114 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2114 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2114 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2114 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2115 -- apt-get -y update && lxc-attach -n debLXC2115 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2115 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2115 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2115 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2116 -- apt-get -y update && lxc-attach -n debLXC2116 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2116 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2116 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2116 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2117 -- apt-get -y update && lxc-attach -n debLXC2117 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2117 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2117 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2117 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2118 -- apt-get -y update && lxc-attach -n debLXC2118 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2118 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2118 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2118 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2119 -- apt-get -y update && lxc-attach -n debLXC2119 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2119 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2119 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2119 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2120 -- apt-get -y update && lxc-attach -n debLXC2120 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2120 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2120 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2120 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2121 -- apt-get -y update && lxc-attach -n debLXC2121 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2121 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2121 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2121 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2122 -- apt-get -y update && lxc-attach -n debLXC2122 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2122 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2122 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2122 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2123 -- apt-get -y update && lxc-attach -n debLXC2123 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2123 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2123 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2123 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2124 -- apt-get -y update && lxc-attach -n debLXC2124 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2124 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2124 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2124 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &
lxc-attach -n debLXC2125 -- apt-get -y update && lxc-attach -n debLXC2125 -- apt-get install -y php5-cli php5-gd wget && lxc-attach -n debLXC2125 wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2125 -- dpkg -i phoronix-test-suite_7.0.1_all.deb && lxc-attach -n debLXC2125 phoronix-test-suite phoromatic.connect 10.22.9.17:8080/IVENVZ &

